// Re-export canonical types from types.ts for backward compat
export type {
  Outcome,
  Grade,
  ReviewConclusion,
  BettingDirection,
  CompletionStatus,
  ScoreItemData,
  ScoreData,
  HandicapValue,
  HandicapDeduction,
  BetSlip,
  BetRecord,
  AbandonedRecord,
  UnifiedRecord,
} from "./types";

export { calcPnl, getTotalBetAmount, getTotalPnl } from "./types";

import type { BetRecord, AbandonedRecord, HandicapDeduction } from "./types";

// ─── Shared empty deduction (for mock records) ────────────────────────────────

const emptyDeduction: HandicapDeduction = {
  fairRanges: { side: "", values: [] },
  homeWinBookieExpected: { side: "", values: [] },
  awayWinBookieExpected: { side: "", values: [] },
  reverseProbability: "", suspectedTrap: false, doubts: "",
};

// ─── Mock Bet Records ─────────────────────────────────────────────────────────

export const mockDetailedRecords: BetRecord[] = [
  {
    id: "1",
    type: "bet",
    match: "英超 曼城 vs 阿森纳",
    homeTeam: "曼城",
    awayTeam: "阿森纳",
    kickoffTime: "2026-04-11T20:00",
    bettingDirection: "home",
    handicapSide: "home",
    handicapValue: "0.75",
    grade: "S",
    totalScore: 10,
    isDisciplineViolation: false,
    deduction: {
      fairRanges: { side: "home", values: ["0.75"] },
      homeWinBookieExpected: { side: "home", values: ["0.5"] },
      awayWinBookieExpected: { side: "away", values: ["0.25"] },
      reverseProbability: "very_low",
      suspectedTrap: false,
      doubts: "",
    },
    scores: {
      fundamental: {
        score: 2,
        tags: ["状态支撑盘口", "热门过热"],
        note: "曼城近5场主场全胜，阿森纳客场状态起伏，热度差明显但盘口支撑",
      },
      odds: { score: 2, tags: ["开盘出发点清晰", "应得盘合理"], note: "" },
      reliability: {
        score: 2,
        tags: ["安全边界足够", "想得清楚"],
        note: "判断逻辑清晰，信息充分，无冲动成分",
      },
      trap: { score: 2, tags: ["无明显嫌疑"], note: "" },
      bookie: {
        score: 2,
        tags: ["立场清晰", "有明确反向支撑"],
        note: "庄家持续收曼城方向，盘口无异动",
      },
    },
    bets: [
      {
        id: "b1",
        type: "pre",
        handicapSide: "home",
        handicapValue: "0.75",
        odds: 0.92,
        amount: 22000,
        betTime: "2026-04-11T14:32",
      },
    ],
    result: {
      outcome: "half_win",
      errors: [],
      reviewNote: "执行完全符合S级标准，赢半结果合理，纪律执行良好。",
    },
    completionStatus: "complete",
    createdAt: "2026-04-11T14:30:00",
  },
  {
    id: "2",
    type: "bet",
    match: "西甲 皇马 vs 巴塞罗那",
    homeTeam: "皇马",
    awayTeam: "巴塞罗那",
    kickoffTime: "2026-04-09T21:00",
    bettingDirection: "home",
    handicapSide: "home",
    handicapValue: "0.5",
    grade: "B",
    totalScore: 8,
    isDisciplineViolation: true, // reliability failed but bet anyway
    deduction: emptyDeduction,
    scores: {
      fundamental: { score: 2, tags: ["强弱分明过头", "状态支撑盘口"], note: "" },
      odds: { score: 2, tags: ["应得盘合理", "盘口偏浅"], note: "浅盘但出发点合理" },
      reliability: {
        score: 0,
        tags: ["信息不完整"],
        note: "伤停名单未完全确认，仍然选择下注",
      },
      trap: { score: 2, tags: ["无明显嫌疑"], note: "" },
      bookie: { score: 2, tags: ["立场清晰"], note: "" },
    },
    bets: [
      {
        id: "b2",
        type: "pre",
        handicapSide: "home",
        handicapValue: "0.5",
        odds: 0.88,
        amount: 8000,
        betTime: "2026-04-09T16:10",
      },
    ],
    result: {
      outcome: "win",
      errors: ["应放弃却没放弃", "不该下却下了"],
      reviewNote:
        "结果赢了，但可靠性未通过（半硬门槛）却仍然执行，这次是运气。下次遇到可靠性不足必须坚决放弃。",
    },
    completionStatus: "complete",
    createdAt: "2026-04-09T16:00:00",
  },
  {
    id: "3",
    type: "bet",
    match: "德甲 拜仁 vs 多特蒙德",
    homeTeam: "拜仁",
    awayTeam: "多特蒙德",
    kickoffTime: "2026-04-13T21:30",
    bettingDirection: "home",
    handicapSide: "home",
    handicapValue: "1",
    grade: "C",
    totalScore: 6,
    isDisciplineViolation: false,
    deduction: emptyDeduction,
    scores: {
      fundamental: { score: 2, tags: ["热门过热", "状态支撑盘口"], note: "" },
      odds: {
        score: 0,
        tags: ["盘口偏深", "热门过于便宜"],
        note: "主让1球赔率仅0.85，性价比低",
      },
      reliability: { score: 2, tags: ["想得清楚"], note: "" },
      trap: {
        score: 0,
        tags: ["存在明显嫌疑"],
        note: "开赛前2小时盘口突然移动，有抽水嫌疑",
      },
      bookie: { score: 2, tags: ["与大众一致但未强化"], note: "" },
    },
    bets: [
      {
        id: "b3",
        type: "live",
        handicapSide: "home",
        handicapValue: "1",
        odds: 0.85,
        amount: 6000,
        betTime: "2026-04-13T21:50",
      },
    ],
    // pending_review — kickoff is in the past, no result yet
    completionStatus: "pending_review",
    createdAt: "2026-04-13T21:45:00",
  },
  {
    id: "4",
    type: "bet",
    match: "英超 利物浦 vs 切尔西",
    homeTeam: "利物浦",
    awayTeam: "切尔西",
    kickoffTime: "2026-04-06T16:30",
    bettingDirection: "home",
    handicapSide: "home",
    handicapValue: "0.5",
    grade: "A",
    totalScore: 10,
    isDisciplineViolation: false,
    deduction: emptyDeduction,
    scores: {
      fundamental: { score: 2, tags: ["状态支撑盘口", "战意真实可用"], note: "" },
      odds: { score: 2, tags: ["开盘出发点清晰", "应得盘合理"], note: "" },
      reliability: { score: 2, tags: ["安全边界足够", "想得清楚"], note: "" },
      trap: { score: 2, tags: ["无明显嫌疑"], note: "" },
      bookie: { score: 2, tags: ["立场清晰", "有明确反向支撑"], note: "" },
    },
    bets: [
      {
        id: "b4",
        type: "pre",
        handicapSide: "home",
        handicapValue: "0.5",
        odds: 0.9,
        amount: 15000,
        betTime: "2026-04-06T10:20",
      },
    ],
    result: {
      outcome: "loss",
      errors: ["基本面误判"],
      reviewNote: "利物浦当日临时伤停主力，信息未及时更新。需要完善伤停信息核查流程。",
    },
    completionStatus: "complete",
    createdAt: "2026-04-06T10:00:00",
  },
  {
    id: "5",
    type: "bet",
    match: "意甲 AC米兰 vs 国际米兰",
    homeTeam: "AC米兰",
    awayTeam: "国际米兰",
    kickoffTime: "2026-04-03T21:45",
    bettingDirection: "away",
    handicapSide: "home",
    handicapValue: "0.5",
    grade: "A",
    totalScore: 10,
    isDisciplineViolation: false,
    deduction: emptyDeduction,
    scores: {
      fundamental: { score: 2, tags: ["状态支撑盘口"], note: "" },
      odds: { score: 2, tags: ["应得盘合理"], note: "" },
      reliability: { score: 2, tags: ["安全边界足够"], note: "" },
      trap: { score: 2, tags: ["无明显嫌疑"], note: "" },
      bookie: { score: 2, tags: ["立场清晰"], note: "" },
    },
    bets: [
      {
        id: "b5",
        type: "pre",
        handicapSide: "away",
        handicapValue: "0.5",
        odds: 0.9,
        amount: 15000,
        betTime: "2026-04-03T10:00",
      },
    ],
    result: {
      outcome: "win",
      errors: [],
      reviewNote: "客队状态更稳，判断准确，执行到位。",
    },
    completionStatus: "complete",
    createdAt: "2026-04-03T10:00:00",
  },
];

// ─── Mock Abandoned Records ───────────────────────────────────────────────────

export const mockAbandonedRecords: AbandonedRecord[] = [
  {
    id: "a1",
    type: "abandoned",
    match: "意甲 尤文图斯 vs 那不勒斯",
    homeTeam: "尤文图斯",
    awayTeam: "那不勒斯",
    kickoffTime: "2026-04-10T21:45",
    bettingDirection: "home",
    handicapSide: "home",
    handicapValue: "0.5",
    totalScore: 8,
    abandonReason: "庄家立场复核未通过（硬门槛）",
    deduction: {
      fairRanges: { side: "home", values: ["0.5"] },
      homeWinBookieExpected: { side: "", values: [] },
      awayWinBookieExpected: { side: "", values: [] },
      reverseProbability: "somewhat",
      suspectedTrap: false,
      doubts: "庄家盘口来回拉锯，方向不明确",
    },
    scores: {
      fundamental: { score: 2, tags: ["强弱分明过头"], note: "" },
      odds: { score: 2, tags: ["开盘出发点清晰"], note: "" },
      reliability: { score: 2, tags: ["安全边界足够"], note: "" },
      trap: { score: 2, tags: ["无明显嫌疑"], note: "" },
      bookie: {
        score: 0,
        tags: ["立场暧昧"],
        note: "庄家盘口来回拉锯，开赛前方向仍不明确",
      },
    },
    actualResult: "win",
    reviewConclusion: "no_regret",
    reviewNote: "赢了，但庄家立场确实模糊。硬门槛存在就是为了这种情况，不后悔放弃。",
    completionStatus: "complete",
    createdAt: "2026-04-10T14:00:00",
  },
  {
    id: "a2",
    type: "abandoned",
    match: "法甲 巴黎圣日耳曼 vs 里昂",
    homeTeam: "巴黎圣日耳曼",
    awayTeam: "里昂",
    kickoffTime: "2026-04-08T21:00",
    bettingDirection: "home",
    handicapSide: "home",
    handicapValue: "1.5",
    totalScore: 4,
    abandonReason: "综合评分过低（4/10），基本面与赔率均未通过",
    deduction: emptyDeduction,
    scores: {
      fundamental: {
        score: 0,
        tags: ["历史形象易误导"],
        note: "主场大让盘历史上鲜少走出，热度高，容易被形象误导",
      },
      odds: {
        score: 0,
        tags: ["盘口偏深", "高低水有引导"],
        note: "1.5让盘赔率仅0.72，明显有引导嫌疑",
      },
      reliability: { score: 2, tags: ["想得清楚"], note: "" },
      trap: { score: 0, tags: ["存在明显嫌疑"], note: "大热必输结构" },
      bookie: { score: 2, tags: ["立场清晰"], note: "" },
    },
    actualResult: "loss",
    reviewConclusion: "abandon_correct",
    reviewNote: "输球印证了当时判断。大让盘低赔率是陷阱，放弃完全正确。",
    completionStatus: "complete",
    createdAt: "2026-04-08T14:00:00",
  },
  {
    id: "a3",
    type: "abandoned",
    match: "西甲 巴塞罗那 vs 马德里竞技",
    homeTeam: "巴塞罗那",
    awayTeam: "马德里竞技",
    kickoffTime: "2026-04-05T20:00",
    bettingDirection: "home",
    handicapSide: "home",
    handicapValue: "0.75",
    totalScore: 6,
    abandonReason: "可靠性不足，信息不完整",
    deduction: emptyDeduction,
    scores: {
      fundamental: { score: 2, tags: ["状态支撑盘口"], note: "" },
      odds: { score: 2, tags: ["应得盘合理"], note: "" },
      reliability: {
        score: 0,
        tags: ["信息不完整", "值得放弃"],
        note: "关键球员状态不明，未能确认",
      },
      trap: { score: 0, tags: ["存在明显嫌疑"], note: "" },
      bookie: { score: 2, tags: ["立场清晰"], note: "" },
    },
    actualResult: "win",
    reviewConclusion: "no_regret",
    reviewNote: "赢了但当时信息确实不够，可靠性不足就应该放弃，结果不能为过程辩护。",
    completionStatus: "complete",
    createdAt: "2026-04-05T12:00:00",
  },
  {
    id: "a4",
    type: "abandoned",
    match: "英超 阿斯顿维拉 vs 热刺",
    homeTeam: "阿斯顿维拉",
    awayTeam: "热刺",
    kickoffTime: "2026-04-12T16:00",
    bettingDirection: "away",
    handicapSide: "home",
    handicapValue: "0.25",
    totalScore: 2,
    abandonReason: "庄家立场未通过且综合评分过低",
    deduction: emptyDeduction,
    scores: {
      fundamental: { score: 0, tags: ["历史形象易误导"], note: "" },
      odds: { score: 0, tags: ["盘口偏深"], note: "" },
      reliability: { score: 0, tags: ["信息不完整"], note: "" },
      trap: { score: 0, tags: ["存在明显嫌疑"], note: "" },
      bookie: { score: 2, tags: ["立场清晰"], note: "" },
    },
    // not yet reviewed after match
    completionStatus: "pending_review",
    createdAt: "2026-04-12T10:00:00",
  },
];

// ─── Dashboard Stats (computed from mock) ────────────────────────────────────

export const mockStats = {
  totalMatches: 5,
  totalPnl: 12400,
  totalBetAmount: 66000,
  roi: 18.8,
  thisMonthPnl: 7440,
  thisMonthBetAmount: 51000,
  thisMonthRoi: 14.6,
  monthlyTarget: 20000,
  weeklyTarget: 5000,
  yearlyTarget: 200000,
  thisWeekPnl: 3200,
  hitRate: 60.0,
  disciplineRate: 80.0,      // % of times discipline was followed
  pendingReviewCount: 1,     // records awaiting post-match review
  streak: { type: "win" as const, count: 2 },
  results: { win: 3, halfWin: 1, push: 0, halfLoss: 0, loss: 1 },
  today: {
    matches: 1,
    totalAmount: 6000,
    remainingQuota: 9000,
  },
};
